/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ES;

import java.awt.Toolkit;

/**
 *
 * @author Asus
 */
public class หญิง_ยาว_เกล้า extends javax.swing.JFrame {

    /**
     * Creates new form หญิง_ยาว_เกล้า
     */
    public หญิง_ยาว_เกล้า() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        พุ่มทรงข้าวบิณฑ์ = new javax.swing.JRadioButton();
        มุ่นมวยเป็นทรงกลม = new javax.swing.JRadioButton();
        กระพุ่มเรียงสูง = new javax.swing.JRadioButton();
        ผมปีกมีจอนผม = new javax.swing.JRadioButton();
        หนูนหยิกรักแครง = new javax.swing.JRadioButton();
        โซงโขดง = new javax.swing.JRadioButton();
        ย้อนกลับ = new javax.swing.JButton();
        ต่อไป = new javax.swing.JButton();
        เกล้าผมกลางศีรษะ = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Expert system of hairstyles evolution since the past until the present.");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("DSU_MonTaNa", 1, 48)); // NOI18N
        jLabel1.setText("เกล้าผม");

        พุ่มทรงข้าวบิณฑ์.setFont(new java.awt.Font("DSU_MaiThai", 0, 24)); // NOI18N
        พุ่มทรงข้าวบิณฑ์.setText("พุ่มทรงข้าวบิณฑ์");
        พุ่มทรงข้าวบิณฑ์.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                พุ่มทรงข้าวบิณฑ์ActionPerformed(evt);
            }
        });

        มุ่นมวยเป็นทรงกลม.setFont(new java.awt.Font("DSU_MaiThai", 0, 24)); // NOI18N
        มุ่นมวยเป็นทรงกลม.setText("มุ่นมวยเป็นทรงกลม");
        มุ่นมวยเป็นทรงกลม.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                มุ่นมวยเป็นทรงกลมActionPerformed(evt);
            }
        });

        กระพุ่มเรียงสูง.setFont(new java.awt.Font("DSU_MaiThai", 0, 24)); // NOI18N
        กระพุ่มเรียงสูง.setText("กระพุ่มเรียงสูง");
        กระพุ่มเรียงสูง.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                กระพุ่มเรียงสูงActionPerformed(evt);
            }
        });

        ผมปีกมีจอนผม.setFont(new java.awt.Font("DSU_MaiThai", 0, 24)); // NOI18N
        ผมปีกมีจอนผม.setText("ผมปีกมีจอนผม");
        ผมปีกมีจอนผม.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ผมปีกมีจอนผมActionPerformed(evt);
            }
        });

        หนูนหยิกรักแครง.setFont(new java.awt.Font("DSU_MaiThai", 0, 24)); // NOI18N
        หนูนหยิกรักแครง.setText("หนูนหยิกรักแครง");
        หนูนหยิกรักแครง.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                หนูนหยิกรักแครงActionPerformed(evt);
            }
        });

        โซงโขดง.setFont(new java.awt.Font("DSU_MaiThai", 0, 24)); // NOI18N
        โซงโขดง.setText("โซงโขดง");
        โซงโขดง.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                โซงโขดงActionPerformed(evt);
            }
        });

        ย้อนกลับ.setFont(new java.awt.Font("DSU_MaiThai", 1, 18)); // NOI18N
        ย้อนกลับ.setText("ย้อนกลับ");
        ย้อนกลับ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ย้อนกลับActionPerformed(evt);
            }
        });

        ต่อไป.setFont(new java.awt.Font("DSU_MaiThai", 1, 18)); // NOI18N
        ต่อไป.setText("ต่อไป");
        ต่อไป.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ต่อไปActionPerformed(evt);
            }
        });

        เกล้าผมกลางศีรษะ.setFont(new java.awt.Font("DSU_MaiThai", 0, 24)); // NOI18N
        เกล้าผมกลางศีรษะ.setText("เกล้าผมกลางศีรษะ");
        เกล้าผมกลางศีรษะ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                เกล้าผมกลางศีรษะActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(ย้อนกลับ)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ต่อไป, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(325, 325, 325))
            .addGroup(layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(พุ่มทรงข้าวบิณฑ์)
                    .addComponent(โซงโขดง)
                    .addComponent(เกล้าผมกลางศีรษะ))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ผมปีกมีจอนผม)
                    .addComponent(มุ่นมวยเป็นทรงกลม))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(หนูนหยิกรักแครง)
                    .addComponent(กระพุ่มเรียงสูง))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(มุ่นมวยเป็นทรงกลม)
                    .addComponent(กระพุ่มเรียงสูง)
                    .addComponent(พุ่มทรงข้าวบิณฑ์))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ผมปีกมีจอนผม)
                    .addComponent(หนูนหยิกรักแครง)
                    .addComponent(เกล้าผมกลางศีรษะ))
                .addGap(34, 34, 34)
                .addComponent(โซงโขดง)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ย้อนกลับ)
                    .addComponent(ต่อไป))
                .addGap(31, 31, 31))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ย้อนกลับActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ย้อนกลับActionPerformed
        new หญิง_ยาว().setVisible(true);
        dispose();
    }//GEN-LAST:event_ย้อนกลับActionPerformed

    private void ต่อไปActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ต่อไปActionPerformed
        if(พุ่มทรงข้าวบิณฑ์.isSelected()){
            new หญิง_ยาว_เกล้า_พุ่มทรงข้าวบิณฑ์().setVisible(true);
            dispose();
        }
        else if(กระพุ่มเรียงสูง.isSelected()){
            new หญิง_ยาว_เกล้า_กระพุ่มเรียงสูง().setVisible(true);
            dispose();
        }
        else if(ผมปีกมีจอนผม.isSelected()){
            new หญิง_ยาว_เกล้า_ปีกมีจอน().setVisible(true);
            dispose();
        }
        else if(มุ่นมวยเป็นทรงกลม.isSelected()){
            new หญิง_ยาว_เกล้า_มุ่นมวยเป็นทรงกลม().setVisible(true);
            dispose();
        }
        else if(หนูนหยิกรักแครง.isSelected()){
            new หญิง_ยาว_เกล้า_หนูนหยิกรักแครง().setVisible(true);
            dispose();
        }
        else if(เกล้าผมกลางศีรษะ.isSelected()){
            new หญิง_ยาว_เกล้า_กลางศีรษะ().setVisible(true);
            dispose();
        }
        else if(โซงโขดง.isSelected()){
            new หญิง_ยาว_เกล้า_โซงโขดง().setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_ต่อไปActionPerformed

    private void พุ่มทรงข้าวบิณฑ์ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_พุ่มทรงข้าวบิณฑ์ActionPerformed
        if(พุ่มทรงข้าวบิณฑ์.isSelected()) {
            กระพุ่มเรียงสูง.setSelected(false);
            ผมปีกมีจอนผม.setSelected(false);
            มุ่นมวยเป็นทรงกลม.setSelected(false);
            หนูนหยิกรักแครง.setSelected(false);
            เกล้าผมกลางศีรษะ.setSelected(false);
            โซงโขดง.setSelected(false);
        }
    }//GEN-LAST:event_พุ่มทรงข้าวบิณฑ์ActionPerformed

    private void มุ่นมวยเป็นทรงกลมActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_มุ่นมวยเป็นทรงกลมActionPerformed
         if(มุ่นมวยเป็นทรงกลม.isSelected()) {
            กระพุ่มเรียงสูง.setSelected(false);
            ผมปีกมีจอนผม.setSelected(false);
            พุ่มทรงข้าวบิณฑ์.setSelected(false);
            หนูนหยิกรักแครง.setSelected(false);
            เกล้าผมกลางศีรษะ.setSelected(false);
            โซงโขดง.setSelected(false);
        }
    }//GEN-LAST:event_มุ่นมวยเป็นทรงกลมActionPerformed

    private void กระพุ่มเรียงสูงActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_กระพุ่มเรียงสูงActionPerformed
        if(กระพุ่มเรียงสูง.isSelected()) {
            มุ่นมวยเป็นทรงกลม.setSelected(false);
            ผมปีกมีจอนผม.setSelected(false);
            พุ่มทรงข้าวบิณฑ์.setSelected(false);
            หนูนหยิกรักแครง.setSelected(false);
            เกล้าผมกลางศีรษะ.setSelected(false);
            โซงโขดง.setSelected(false);
        }
    }//GEN-LAST:event_กระพุ่มเรียงสูงActionPerformed

    private void เกล้าผมกลางศีรษะActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_เกล้าผมกลางศีรษะActionPerformed
        if(เกล้าผมกลางศีรษะ.isSelected()) {
            มุ่นมวยเป็นทรงกลม.setSelected(false);
            ผมปีกมีจอนผม.setSelected(false);
            พุ่มทรงข้าวบิณฑ์.setSelected(false);
            หนูนหยิกรักแครง.setSelected(false);
            กระพุ่มเรียงสูง.setSelected(false);
            โซงโขดง.setSelected(false);
        }
    }//GEN-LAST:event_เกล้าผมกลางศีรษะActionPerformed

    private void ผมปีกมีจอนผมActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ผมปีกมีจอนผมActionPerformed
        if(ผมปีกมีจอนผม.isSelected()) {
            มุ่นมวยเป็นทรงกลม.setSelected(false);
            เกล้าผมกลางศีรษะ.setSelected(false);
            พุ่มทรงข้าวบิณฑ์.setSelected(false);
            หนูนหยิกรักแครง.setSelected(false);
            กระพุ่มเรียงสูง.setSelected(false);
            โซงโขดง.setSelected(false);
        }
    }//GEN-LAST:event_ผมปีกมีจอนผมActionPerformed

    private void หนูนหยิกรักแครงActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_หนูนหยิกรักแครงActionPerformed
        if(หนูนหยิกรักแครง.isSelected()) {
            มุ่นมวยเป็นทรงกลม.setSelected(false);
            เกล้าผมกลางศีรษะ.setSelected(false);
            พุ่มทรงข้าวบิณฑ์.setSelected(false);
            ผมปีกมีจอนผม.setSelected(false);
            กระพุ่มเรียงสูง.setSelected(false);
            โซงโขดง.setSelected(false);
        }
    }//GEN-LAST:event_หนูนหยิกรักแครงActionPerformed

    private void โซงโขดงActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_โซงโขดงActionPerformed
        if(โซงโขดง.isSelected()) {
            มุ่นมวยเป็นทรงกลม.setSelected(false);
            เกล้าผมกลางศีรษะ.setSelected(false);
            พุ่มทรงข้าวบิณฑ์.setSelected(false);
            หนูนหยิกรักแครง.setSelected(false);
            กระพุ่มเรียงสูง.setSelected(false);
            ผมปีกมีจอนผม.setSelected(false);
        }
    }//GEN-LAST:event_โซงโขดงActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(หญิง_ยาว_เกล้า.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(หญิง_ยาว_เกล้า.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(หญิง_ยาว_เกล้า.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(หญิง_ยาว_เกล้า.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new หญิง_ยาว_เกล้า().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton กระพุ่มเรียงสูง;
    private javax.swing.JButton ต่อไป;
    private javax.swing.JRadioButton ผมปีกมีจอนผม;
    private javax.swing.JRadioButton พุ่มทรงข้าวบิณฑ์;
    private javax.swing.JRadioButton มุ่นมวยเป็นทรงกลม;
    private javax.swing.JButton ย้อนกลับ;
    private javax.swing.JRadioButton หนูนหยิกรักแครง;
    private javax.swing.JRadioButton เกล้าผมกลางศีรษะ;
    private javax.swing.JRadioButton โซงโขดง;
    // End of variables declaration//GEN-END:variables
}
