/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ES;

import java.awt.Toolkit;

/**
 *
 * @author Asus
 */
public class หญิง_บ่า_ปล่อย extends javax.swing.JFrame {

    /**
     * Creates new form หญิง_บ่า_ปล่อยผม
     */
    public หญิง_บ่า_ปล่อย() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ผมบ๊อบ = new javax.swing.JRadioButton();
        ผมตรง = new javax.swing.JRadioButton();
        ผมดัดลอน = new javax.swing.JRadioButton();
        ผมซิงเกิ้ล = new javax.swing.JRadioButton();
        ผมอีตันคร๊อพ = new javax.swing.JRadioButton();
        ย้อนกลับ = new javax.swing.JButton();
        ต่อไป = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Expert system of hairstyles evolution since the past until the present.");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("DSU_MonTaNa", 1, 48)); // NOI18N
        jLabel1.setText("ปล่อยผม");

        ผมบ๊อบ.setFont(new java.awt.Font("DSU_MaiThai", 0, 24)); // NOI18N
        ผมบ๊อบ.setText("ผมบ๊อบ");
        ผมบ๊อบ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ผมบ๊อบActionPerformed(evt);
            }
        });

        ผมตรง.setFont(new java.awt.Font("DSU_MaiThai", 0, 24)); // NOI18N
        ผมตรง.setText("ผมตรง");
        ผมตรง.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ผมตรงActionPerformed(evt);
            }
        });

        ผมดัดลอน.setFont(new java.awt.Font("DSU_MaiThai", 0, 24)); // NOI18N
        ผมดัดลอน.setText("ผมดัดลอน");
        ผมดัดลอน.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ผมดัดลอนActionPerformed(evt);
            }
        });

        ผมซิงเกิ้ล.setFont(new java.awt.Font("DSU_MaiThai", 0, 24)); // NOI18N
        ผมซิงเกิ้ล.setText("ผมซิงเกิ้ล");
        ผมซิงเกิ้ล.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ผมซิงเกิ้ลActionPerformed(evt);
            }
        });

        ผมอีตันคร๊อพ.setFont(new java.awt.Font("DSU_MaiThai", 0, 24)); // NOI18N
        ผมอีตันคร๊อพ.setText("ผมอีตันคร๊อพ");
        ผมอีตันคร๊อพ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ผมอีตันคร๊อพActionPerformed(evt);
            }
        });

        ย้อนกลับ.setFont(new java.awt.Font("DSU_MaiThai", 1, 18)); // NOI18N
        ย้อนกลับ.setText("ย้อนกลับ");
        ย้อนกลับ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ย้อนกลับActionPerformed(evt);
            }
        });

        ต่อไป.setFont(new java.awt.Font("DSU_MaiThai", 1, 18)); // NOI18N
        ต่อไป.setText("ต่อไป");
        ต่อไป.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ต่อไปActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ผมบ๊อบ)
                            .addComponent(ผมซิงเกิ้ล))
                        .addGap(85, 85, 85)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ผมตรง)
                                .addGap(86, 86, 86)
                                .addComponent(ผมดัดลอน))
                            .addComponent(ผมอีตันคร๊อพ)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(141, 141, 141)))
                .addGap(0, 172, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(ย้อนกลับ)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ต่อไป, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ผมบ๊อบ)
                    .addComponent(ผมตรง)
                    .addComponent(ผมดัดลอน))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ผมซิงเกิ้ล)
                    .addComponent(ผมอีตันคร๊อพ))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ย้อนกลับ)
                    .addComponent(ต่อไป))
                .addGap(28, 28, 28))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ต่อไปActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ต่อไปActionPerformed
        if(ผมซิงเกิ้ล.isSelected()){
            new หญิง_บ่า_ปล่อย_ซิงเกิ้ล().setVisible(true);
            dispose();
        }
        else if(ผมตรง.isSelected()){
            new หญิง_บ่า_ปล่อย_ตรง().setVisible(true);
            dispose();
        }
        else if(ผมอีตันคร๊อพ.isSelected()){
            new หญิง_บ่า_ปล่อย_อีตันคร๊อพ().setVisible(true);
            dispose();
        }
        else if(ผมดัดลอน.isSelected()){
            new หญิง_บ่า_ปล่อย_ดัดลอน().setVisible(true);
            dispose();
        }
        else if(ผมบ๊อบ.isSelected()){
            new หญิง_บ่า_ปล่อย_บ๊อบ().setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_ต่อไปActionPerformed

    private void ย้อนกลับActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ย้อนกลับActionPerformed
          new หญิง_บ่า().setVisible(true);
        dispose();
    }//GEN-LAST:event_ย้อนกลับActionPerformed

    private void ผมบ๊อบActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ผมบ๊อบActionPerformed
        if(ผมบ๊อบ.isSelected()) {
            ผมซิงเกิ้ล.setSelected(false);
            ผมดัดลอน.setSelected(false);
            ผมตรง.setSelected(false);
            ผมอีตันคร๊อพ.setSelected(false);
        }
    }//GEN-LAST:event_ผมบ๊อบActionPerformed

    private void ผมตรงActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ผมตรงActionPerformed
        if(ผมบ๊อบ.isSelected()) {
            ผมซิงเกิ้ล.setSelected(false);
            ผมดัดลอน.setSelected(false);
            ผมตรง.setSelected(false);
            ผมอีตันคร๊อพ.setSelected(false);
        }
    }//GEN-LAST:event_ผมตรงActionPerformed

    private void ผมดัดลอนActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ผมดัดลอนActionPerformed
        if(ผมดัดลอน.isSelected()) {
            ผมซิงเกิ้ล.setSelected(false);
            ผมบ๊อบ.setSelected(false);
            ผมตรง.setSelected(false);
            ผมอีตันคร๊อพ.setSelected(false);
        }
    }//GEN-LAST:event_ผมดัดลอนActionPerformed

    private void ผมซิงเกิ้ลActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ผมซิงเกิ้ลActionPerformed
        if(ผมซิงเกิ้ล.isSelected()) {
            ผมบ๊อบ.setSelected(false);
            ผมดัดลอน.setSelected(false);
            ผมตรง.setSelected(false);
            ผมอีตันคร๊อพ.setSelected(false);
        }
    }//GEN-LAST:event_ผมซิงเกิ้ลActionPerformed

    private void ผมอีตันคร๊อพActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ผมอีตันคร๊อพActionPerformed
        if(ผมอีตันคร๊อพ.isSelected()) {
            ผมซิงเกิ้ล.setSelected(false);
            ผมดัดลอน.setSelected(false);
            ผมตรง.setSelected(false);
            ผมบ๊อบ.setSelected(false);
        }
    }//GEN-LAST:event_ผมอีตันคร๊อพActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(หญิง_บ่า_ปล่อย.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(หญิง_บ่า_ปล่อย.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(หญิง_บ่า_ปล่อย.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(หญิง_บ่า_ปล่อย.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new หญิง_บ่า_ปล่อย().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton ต่อไป;
    private javax.swing.JRadioButton ผมซิงเกิ้ล;
    private javax.swing.JRadioButton ผมดัดลอน;
    private javax.swing.JRadioButton ผมตรง;
    private javax.swing.JRadioButton ผมบ๊อบ;
    private javax.swing.JRadioButton ผมอีตันคร๊อพ;
    private javax.swing.JButton ย้อนกลับ;
    // End of variables declaration//GEN-END:variables
}
